### PR TITLE
Q2A docs (2020 Design)

### PR DESCRIPTION
**Pull request by heliochun**
The site was fully redesigned and every documentation page was copied and recreated in pure HTML.
All files are in a separate folder called "**_docs Q2A 2020 Design**" so you can decide whether you want to translate them to Jekyll or keep the plain HTML files and move it as it is. It's ready to go.

### CODE REVIEW

**Comment by heliochun** [comment]
I was trying to delete the previous commit (Community guidelines) but I think it didn't work.

**Comment by gidgreen** [comment]
Hi, really appreciate all the work you put into making this migration. But have you discussed this idea with @svivian, @pupi1985 or anyone else? Moving from Markdown to HTML is a big change and it may make it harder to do little content changes in future. I'm not saying it's not the right idea, it's just something that I think needs to be discussed.

**Comment by heliochun** [comment]
Hey Gideon. Yes, I told Scott I was developing the new design in plain HTML a while back and he said that's fine. 
I don't know if he wants to keep the files as it is or convert them to jekyll, so that's why I put all files in a separate folder, so you can decide what's best.

**Comment by svivian** [comment]
Sorry forgot to respond to this. The design looks good! We'll be keeping the site as Jekyll, since that makes it much easier for people to contribute. So I'll incorporate your design into the Jekyll template we have.

How did you create all the separate HTML files? Did you use Jekyll or make each one manually?

**Comment by svivian** [comment]
The new design is now live! I've incorporated the design you made into the Jekyll site, with a few changes to fit our workflow. Thanks for the great effort!

**Pull request closed without merging**
